import Header from "@/components/Header";
import type { Metadata } from "next";
import AppWrapper from "./context";

export const metadata: Metadata = {
  title: "Next-Supabase-Shadcn template by Guillaume Duhan",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <AppWrapper>
      <Header />
      {children}
    </AppWrapper>
  );
}
